"""add_model_code_to_chat_message

Revision ID: 5db14ea85dfe
Revises: f19308ec458d
Create Date: 2026-08-08 03:06:03.669036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5db14ea85dfe'
down_revision: Union[str, Sequence[str], None] = 'f19308ec458d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('model_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_chat_message_model_code'), 'chat_message', ['model_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_model_code'), table_name='chat_message')
    op.drop_column('chat_message', 'model_code')
    # ### end Alembic commands ###
