"""add file_ foreign_key for users

Revision ID: 74ec08fd6b8e
Revises: f943dd5ade4a
Create Date: 2026-04-09 17:48:04.160970

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74ec08fd6b8e"
down_revision: Union[str, Sequence[str], None] = "f943dd5ade4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("files")
    op.add_column(
        "users",
        sa.Column("avatar_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(None, "users", "file", ["avatar_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "avatar_id")
    op.create_table(
        "files",
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("files_pkey")),
    )
    # ### end Alembic commands ###
