"""init

Revision ID: a4a79d3e8b7f
Revises:
Create Date: 2026-04-07 21:03:33.126325

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4a79d3e8b7f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),  # 👈 关键
            nullable=False,
        ),
    )
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "is_test")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_test",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
