"""add file url

Revision ID: ac2fba4fac9d
Revises: b8a50251b8c4
Create Date: 2026-04-17 17:08:07.279111

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac2fba4fac9d"
down_revision: Union[str, Sequence[str], None] = "b8a50251b8c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("file", sa.Column("url", sa.String(), nullable=True))
    op.execute("UPDATE file SET url = ''")
    op.alter_column("file", "url", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "url")
    # ### end Alembic commands ###
