"""add file url

Revision ID: b8a50251b8c4
Revises: 74ec08fd6b8e
Create Date: 2026-04-17 17:00:07.602999

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8a50251b8c4"
down_revision: Union[str, Sequence[str], None] = "74ec08fd6b8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file", sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "url")
    # ### end Alembic commands ###
