"""add_server_default_timestamps

Revision ID: f19308ec458d
Revises: 0fb09f0ae365
Create Date: 2026-08-08 02:35:04.241542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19308ec458d'
down_revision: Union[str, Sequence[str], None] = '0fb09f0ae365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_conversation_user_id_is_deleted_updated_at'), table_name='chat_conversation')
    op.drop_index(op.f('ix_chat_message_conversation_id_created_at'), table_name='chat_message')
    op.alter_column('chat_conversation', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('NOW()'),
               existing_nullable=False)
    op.alter_column('chat_conversation', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('NOW()'),
               existing_nullable=False)
    op.alter_column('chat_message', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('NOW()'),
               existing_nullable=False)
    op.alter_column('chat_message_attachment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('NOW()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message_attachment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_message', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_conversation', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_conversation', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_chat_message_conversation_id_created_at'), 'chat_message', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_conversation_user_id_is_deleted_updated_at'), 'chat_conversation', ['user_id', 'is_deleted', 'updated_at'], unique=False)
    # ### end Alembic commands ###
